baseurl = "/"
languageCode = "en-us"
title = "Eric Bryant, PhD"
theme = "hugo-lithium"
googleAnalytics = "UA-154370842-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "CV"
    identifier = "cv"
    pre = "fas fa-address-card"
    url = "/cv/"
    weight = 1
[[menu.main]]
    name = "Posts"
    identifier = "posts"
    pre = "fas fa-list"
    url = "/post/"
    weight = 2

[params]
    owner = "Eric Bryant, PhD"
    description = "A website built with Hugo via blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "dna.ico"

[params.logo]
    url = "landscape.png"
    width = 50
    height = 50
    alt = "Logo"
